engines:
  fixme: 
    enabled: true
  bundler-audit: 
    enabled: true
  duplication: 
    enabled: true
    config: 
      languages:
      - ruby 
  rubocop:
    enabled: true
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- externals/**/*
- bin/**/*
- spec/**/*
